# Generated by Django 2.2.5 on 2019-09-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('washes', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('use', models.CharField(max_length=50)),
                ('wash', models.ManyToManyField(to='washes.Washes')),
            ],
        ),
    ]
