# Generated by Django 2.2.5 on 2019-09-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tools',
            name='wash',
            field=models.ManyToManyField(related_name='tools', to='washes.Washes'),
        ),
    ]
